-- 상위 n개 레코드 
SELECT NAME FROM ANIMAL_INS ORDER BY DATETIME ASC LIMIT 1;

-- 아픈 동물 찾기 
SELECT ANIMAL_ID, NAME FROM ANIMAL_INS WHERE INTAKE_CONDITION = 'Sick' ORDER BY ANIMAL_ID;

-- 나이 정보가 없는 회원 수 구하기
SELECT COUNT(*) FROM USER_INFO WHERE AGE IS NULL;

-- 최솟값 구하기 
SELECT DATETIME FROM ANIMAL_INS ORDER BY DATETIME LIMIT 1;

