-- 동명 동물 수 찾기
SELECT NAME, COUNT(*) AS `COUNT` FROM ANIMAL_INS WHERE NAME IS NOT NULL GROUP BY NAME HAVING COUNT(*) > 1 ORDER BY NAME;
-- NAME IS NULL인 행도 GROUP BY NAME에 포함되어
-- GROUP BY로 묶을 때도 NULL 끼리 하나의 그룹으로 묶인다 

-- 이름에 el이 들어가는 동물 찾기
SELECT ANIMAL_ID, NAME FROM ANIMAL_INS WHERE ANIMAL_TYPE = 'Dog' AND LOWER(NAME) LIKE '%el%' ORDER BY NAME;

-- NULL 처리하기 
SELECT ANIMAL_TYPE, IFNULL(NAME,'No name') AS `NAME`, SEX_UPON_INTAKE FROM ANIMAL_INS  ORDER BY ANIMAL_ID;

-- DATETIME에서 DATE로 형 변환
SELECT ANIMAL_ID, NAME, DATE_FORMAT(DATETIME, '%Y-%m-%d') AS '날짜' FROM ANIMAL_INS ORDER BY ANIMAL_ID;

