-- 동명 동물 수 찾기
SELECT NAME, COUNT(*) AS `COUNT` FROM ANIMAL_INS WHERE NAME IS NOT NULL GROUP BY NAME HAVING COUNT(*) > 1 ORDER BY NAME;
-- NAME IS NULL인 행도 GROUP BY NAME에 포함되어
-- GROUP BY로 묶을 때도 NULL 끼리 하나의 그룹으로 묶인다 


